# Timeout in seconds that Limine will use before automatically booting.
TIMEOUT=5

# The entry name that will be displayed in the boot menu.
/blueOS
    # We use the Limine boot protocol.
    protocol: limine

    # Disable KASLR (it is enabled by default for relocatable kernels)
    kaslr: no

    # Path to the kernel to boot. boot:/// represents the partition on which limine.cfg is located.
    kernel_path: boot():/boot/blueOS

# Same thing, but with KASLR.
/blueOS (with KASLR)
    protocol: limine

    kernel_path: boot():/boot/blueOS